substitutions:
  _IMAGE: asia-southeast1-docker.pkg.dev/tracker-expenses-478512/expenses-repo/expenses-app

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        COMMIT=${COMMIT_SHA:-latest}
        docker build \
          -t ${_IMAGE}:$$COMMIT \
          -t ${_IMAGE}:latest \
          .

  # Push image ke Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        COMMIT=${COMMIT_SHA:-latest}
        docker push ${_IMAGE}:$$COMMIT
        docker push ${_IMAGE}:latest

  # Deploy ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        COMMIT=${COMMIT_SHA:-latest}
        gcloud run deploy new-tracker-expenses-web \
          --image=${_IMAGE}:$$COMMIT \
          --region=asia-southeast1 \
          --platform=managed \
          --allow-unauthenticated \
          --min-instances=0 \
          --max-instances=1 \
          --memory=1Gi \
          --cpu=1 \
          --timeout=300 \
          --concurrency=1 \
          --set-env-vars=GCS_BUCKET=new-tracker-expenses \
          --execution-environment=gen2 \
          --startup-cpu-boost \
          --no-cpu-throttling

images:
  - asia-southeast1-docker.pkg.dev/tracker-expenses-478512/expenses-repo/expenses-app

options:
  logging: CLOUD_LOGGING_ONLY
